apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice1
  template:
    metadata:
      labels:
        app: microservice1
    spec:
      containers:
      - name: microservice1
        image: us-central1-docker.pkg.dev/kubernetes-assignment-429023/kuber-repo/microservice1:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: persistent-storage
          mountPath: /persistent_storage
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: k8s-pvc
